# Generated by Django 3.2.9 on 2021-12-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('entradas', models.CharField(max_length=255)),
                ('saidas', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Estoque',
            },
        ),
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_de_custo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('preco_de_venda', models.DecimalField(decimal_places=2, max_digits=6)),
                ('porcentagem', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Preço',
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('colecao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Produtos',
            },
        ),
    ]
