# Generated by Django 3.2.9 on 2021-12-02 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produtos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.produtos'),
        ),
        migrations.AddField(
            model_name='preco',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.produtos'),
        ),
    ]
