# Generated by Django 3.2.9 on 2021-12-02 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20211202_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_de_custo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('preco_de_venda', models.DecimalField(decimal_places=2, max_digits=6)),
                ('porcentagem', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantidade', models.IntegerField()),
                ('entradas', models.CharField(max_length=255)),
                ('saidas', models.CharField(max_length=255)),
                ('cor', models.CharField(max_length=255)),
                ('tamanho', models.CharField(max_length=255)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.produtos')),
            ],
            options={
                'verbose_name': 'Variante',
            },
        ),
        migrations.RemoveField(
            model_name='preco',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Estoque',
        ),
        migrations.DeleteModel(
            name='Preco',
        ),
    ]
