# Generated by Django 3.2.9 on 2021-12-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_auto_20211202_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variante',
            name='entradas',
        ),
        migrations.RemoveField(
            model_name='variante',
            name='saidas',
        ),
        migrations.AlterField(
            model_name='variante',
            name='cor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='variante',
            name='tamanho',
            field=models.CharField(max_length=50),
        ),
    ]
