# Generated by Django 3.2.9 on 2021-12-02 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item',
        ),
        migrations.RemoveField(
            model_name='ordem',
            name='ordem',
        ),
        migrations.AddField(
            model_name='item',
            name='ordem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordem.ordem'),
        ),
        migrations.AddField(
            model_name='ordem',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordem.cliente'),
        ),
    ]
